//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFacturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int IdCliente { get; set; }
        public string NombreComercial { get; set; }
        public string DocIdentificacion { get; set; }
        public string Estado { get; set; }
    }
}
