//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFacturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int IdEmpleado { get; set; }
        public string NombreEmpleado { get; set; }
        public Nullable<decimal> PorcientoComision { get; set; }
        public string Estado { get; set; }
    }
}
